# Generated by Django 5.2.1 on 2025-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tytulStopien', models.CharField(max_length=255)),
                ('adres_miasto', models.CharField(max_length=255)),
                ('adres_kod_pocztowy', models.CharField(max_length=20)),
                ('adres_ulica', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('imie_nazwisko_celownik', models.CharField(max_length=255)),
                ('imie_nazwisko_biernik', models.CharField(max_length=255)),
                ('imie_nazwisko_dopelniacz', models.CharField(max_length=255)),
            ],
        ),
    ]
