# Generated by Django 5.2.1 on 2025-05-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doktorant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, max_length=255, null=True)),
                ('rozprawa', models.FileField(blank=True, null=True, upload_to='rozprawy/')),
                ('komentarz', models.CharField(blank=True, max_length=255, null=True)),
                ('doktorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doktorant')),
                ('kopromotor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kopromotor_doktoraty', to='core.osoba')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotor_doktoraty', to='core.osoba')),
                ('promotorPomocniczy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotor_pomocniczy_doktoraty', to='core.osoba')),
            ],
        ),
    ]
