# Generated by Django 5.2.1 on 2025-05-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doktorat'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomisjaDr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funkcja', models.CharField(max_length=255)),
                ('data_powolania', models.DateField()),
                ('data_odwolania', models.DateField(blank=True, null=True)),
                ('doktorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doktorat')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.osoba')),
            ],
        ),
    ]
