# Generated by Django 5.2.1 on 2025-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_komisjadr'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktorat',
            name='komisjaDr',
            field=models.ManyToManyField(through='core.KomisjaDr', to='core.osoba'),
        ),
    ]
