# Generated by Django 5.2.1 on 2025-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doktorat_komisjadr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('wydzial', models.CharField(max_length=255)),
                ('adres', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logotypy_RD/')),
            ],
        ),
    ]
