# Generated by Django 5.2.1 on 2025-05-29 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rd'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktorat',
            name='RD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rd'),
        ),
    ]
