# Generated by Django 5.2.1 on 2025-05-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doktorat_rd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_aktywny', models.BooleanField(default=True)),
                ('czy_wyroznienie', models.BooleanField(default=False)),
                ('data_powolania', models.DateField(blank=True, null=True)),
                ('data_recenzji', models.DateField(blank=True, null=True)),
                ('doktorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doktorat')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.osoba')),
            ],
        ),
    ]
