# Generated by Django 5.2.1 on 2025-05-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_szablonzdarzenia_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzablonDokumentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('typ', models.CharField(max_length=255)),
                ('tresc', models.TextField()),
                ('czy_aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DokumentWniosekUchwala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='dokumenty/')),
                ('numer', models.CharField(max_length=50)),
                ('data_utworzenia', models.DateField(auto_now_add=True)),
                ('utworzony_przez', models.CharField(max_length=255)),
                ('doktorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doktorat')),
                ('szablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.szablondokumentu')),
            ],
        ),
    ]
