# Generated by Django 5.2.1 on 2025-05-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_szablondokumentu_dokumentwniosekuchwala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('rola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uprawnienia')),
            ],
        ),
    ]
